#target.collector.default.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  selector:
    app: collector
  clusterIP: None
  ports:
  - name: appport
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: collector
  labels:
    app: collector
spec:
  hostname: target
  subdomain: collector
  containers:
  - name: collector
    image: envoyproxy/envoy-alpine:v1.21-latest
    ports:
    - containerPort: 8080
    command: ["envoy"]
    args: ["-c", "/etc/envoy-config.yaml", "-l", "info"]
    #, "--service-cluster", "'service-a'", "x--service-node", "'service-a'", "--log-format", "'[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v'"]
    volumeMounts:
    - name: envoy-config
      mountPath: /etc/envoy-config.yaml
      subPath: envoy-config.yaml
    - name: envoy-taps
      mountPath: /etc/taps
  - name: app
    image: training/webapp
  volumes:
  - name: envoy-config
    configMap:
      name: collector-envoy-conf
  - name: envoy-taps
    hostPath:
      path: /taps

