#target.original.default.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: target
spec:
  selector:
    app: target
  clusterIP: None
  ports:
  - name: appport
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: target
  labels:
    app: target
spec:
  hostname: target
  subdomain: original
  containers:
  - name: target
    image: training/webapp
